# Generated by Django 4.2.4 on 2023-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('work_group', models.CharField(max_length=100)),
                ('prep', models.CharField(max_length=100)),
                ('dilution', models.CharField(max_length=100)),
                ('analysis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('date_implemented', models.DateField()),
            ],
        ),
    ]
