# Generated by Django 4.2.4 on 2023-08-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_sampledata_delete_analysis_delete_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleData',
            new_name='Sample',
        ),
    ]
